// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package protodecode

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test struct {
	FieldInt32           int32    `protobuf:"varint,1,opt,name=field_int32,json=fieldInt32,proto3" json:"field_int32,omitempty"`
	FieldString          string   `protobuf:"bytes,2,opt,name=field_string,json=fieldString,proto3" json:"field_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_dbd775643803566f, []int{0}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (dst *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(dst, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetFieldInt32() int32 {
	if m != nil {
		return m.FieldInt32
	}
	return 0
}

func (m *Test) GetFieldString() string {
	if m != nil {
		return m.FieldString
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "protodecode.Test")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_dbd775643803566f) }

var fileDescriptor_test_dbd775643803566f = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x06, 0x53, 0x29, 0xa9, 0xc9, 0xf9, 0x29, 0xa9,
	0x4a, 0x5e, 0x5c, 0x2c, 0x21, 0xa9, 0xc5, 0x25, 0x42, 0xf2, 0x5c, 0xdc, 0x69, 0x99, 0xa9, 0x39,
	0x29, 0xf1, 0x99, 0x79, 0x25, 0xc6, 0x46, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x5c, 0x60,
	0x21, 0x4f, 0x90, 0x88, 0x90, 0x22, 0x17, 0x0f, 0x44, 0x41, 0x71, 0x49, 0x51, 0x66, 0x5e, 0xba,
	0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x44, 0x53, 0x30, 0x58, 0x28, 0x89, 0x0d, 0x6c, 0xb0,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x0e, 0x6b, 0x90, 0x6d, 0x00, 0x00, 0x00,
}
